# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1d908f7d5cb979023e7a670777364be9d375d6bd85cde42f350d7b69f50295cd492a1c827840c91608048f43f24e2e86aecb0ea596f69bbd8d093982a826ce23

test:
  secret_key_base: c24bb4415f0474a95854de40b08331640a190ecb217d855194b7dd09efe387d14217a6c539627fa068acb5970b3bc9d19888e4c27bc47703fe1e69b45cd52e53

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
